blank_issues_enabled: true
contact_links:
  - name: Quffen Core Security Policy
    url: https://github.com/quffen/quffen/blob/master/SECURITY.md
    about: View security policy
  - name: Quffen Core Developers
    url: https://bitcoincore.org
    about: Quffen Core homepage
